# Generated by Django 5.0 on 2025-09-01 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patient', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HMOCoveragePlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('consultation_covered', models.BooleanField(default=True)),
                ('consultation_coverage_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('consultation_annual_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('drug_coverage', models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='all', max_length=20)),
                ('drug_coverage_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('drug_annual_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lab_coverage', models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='all', max_length=20)),
                ('lab_coverage_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('lab_annual_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('radiology_coverage', models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='include_selected', max_length=20)),
                ('radiology_coverage_percentage', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('radiology_annual_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('require_verification', models.BooleanField(default=False)),
                ('require_referral', models.BooleanField(default=False)),
                ('annual_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('selected_drugs', models.ManyToManyField(blank=True, related_name='insurance_plans', to='pharmacy.drugmodel')),
                ('selected_lab_tests', models.ManyToManyField(blank=True, related_name='insurance_plans', to='laboratory.labtesttemplatemodel')),
                ('selected_radiology', models.ManyToManyField(blank=True, related_name='insurance_plans', to='scan.scantemplatemodel')),
                ('hmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_plans', to='insurance.hmomodel')),
            ],
        ),
        migrations.AddField(
            model_name='hmomodel',
            name='insurance_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceprovidermodel'),
        ),
        migrations.CreateModel(
            name='PatientInsuranceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('enrollee_id', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('coverage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.hmocoverageplanmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('hmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.hmomodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patient.patientmodel')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('consultation', 'Consultation'), ('drug', 'Drug/Medication'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology/Scan'), ('multiple', 'Multiple Services')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('covered_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('patient_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('service_date', models.DateTimeField()),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL)),
                ('patient_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.patientinsurancemodel')),
            ],
        ),
    ]
