# Generated by Django 5.0 on 2025-08-28 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        ('laboratory', '0003_alter_labtestordermodel_payment_by_and_more'),
        ('patient', '0009_consultationdocument'),
        ('pharmacy', '0003_alter_drugstockoutmodel_worth'),
        ('scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmocoverageplanmodel',
            name='coverage_percentage',
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='consultation_annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='consultation_coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='consultation_covered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='drug_annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='drug_coverage',
            field=models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='drug_coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='lab_annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='lab_coverage',
            field=models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='lab_coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='radiology_annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='radiology_coverage',
            field=models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='include_selected', max_length=20),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='radiology_coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='require_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='require_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_drugs',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='pharmacy.drugmodel'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_lab_tests',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='laboratory.labtesttemplatemodel'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_radiology',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='scan.scantemplatemodel'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hmomodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hmomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hmomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hmomodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovidermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovidermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='enrollee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_insurance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hmocoverageplanmodel',
            name='hmo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_plans', to='insurance.hmomodel'),
        ),
        migrations.AlterField(
            model_name='patientinsurancemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patient.patientmodel'),
        ),
        migrations.CreateModel(
            name='InsuranceClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('consultation', 'Consultation'), ('drug', 'Drug/Medication'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology/Scan'), ('multiple', 'Multiple Services')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('covered_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('patient_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('service_date', models.DateTimeField()),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('patient_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.patientinsurancemodel')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
