# Generated by Django 5.0 on 2025-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
        ('laboratory', '0002_initial'),
        ('patient', '0002_initial'),
        ('pharmacy', '0001_initial'),
        ('scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_drugs',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='pharmacy.drugmodel'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_lab_tests',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='laboratory.labtesttemplatemodel'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_radiology',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='scan.scantemplatemodel'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='hmo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_plans', to='insurance.hmomodel'),
        ),
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hmomodel',
            name='insurance_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceprovidermodel'),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='coverage_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.hmocoverageplanmodel'),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='hmo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.hmomodel'),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='patientinsurancemodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_insurance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='patient_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.patientinsurancemodel'),
        ),
    ]
