# Generated by Django 5.0 on 2025-10-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('insurance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hmomodel',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hmomodel',
            name='contact_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='insuranceclaimmodel',
            name='claim_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('drug', 'Drug/Medication'), ('laboratory', 'Laboratory'), ('scan', 'Radiology/Scan'), ('surgery', 'Surgery'), ('admission', 'Admission'), ('services', 'Services')], max_length=20),
        ),
    ]
