# Generated by Django 5.0 on 2025-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insuranceclaimmodel_approved_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmomodel',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='hmomodel',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
