# Generated by Django 5.0 on 2025-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_initial'),
        ('insurance', '0004_alter_hmomodel_contact_email_alter_hmomodel_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_surgeries',
            field=models.ManyToManyField(blank=True, related_name='insurance_plans', to='inpatient.surgerytype'),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='surgery_annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='surgery_coverage',
            field=models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='include_selected', max_length=20),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='surgery_coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
