# Generated by Django 5.0 on 2025-11-23 10:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_remove_admission_admission_fee_charged_and_more'),
        ('insurance', '0005_hmocoverageplanmodel_selected_surgeries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='admission_annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual limit for admission-related costs', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='admission_coverage',
            field=models.CharField(choices=[('all', 'All'), ('include_selected', 'Include Selected'), ('exclude_selected', 'Exclude Selected'), ('none', 'None')], default='include_selected', help_text='Coverage type for admission/bed fees', max_length=20),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='admission_coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Percentage of admission costs covered by insurance', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='hmocoverageplanmodel',
            name='selected_admission_types',
            field=models.ManyToManyField(blank=True, help_text='Which admission types are covered (if include_selected or exclude_selected)', related_name='insurance_plans', to='inpatient.admissiontype'),
        ),
        migrations.AlterField(
            model_name='insuranceclaimmodel',
            name='claim_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('drug', 'Drug/Medication'), ('laboratory', 'Laboratory'), ('scan', 'Radiology/Scan'), ('surgery', 'Surgery'), ('admission', 'Admission'), ('services', 'Services'), ('ward_round', 'Ward Round')], max_length=20),
        ),
    ]
