# Generated by Django 5.0 on 2026-01-29 09:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultationsessionmodel_admission_and_more'),
        ('inpatient', '0007_admission_admission_activated_date_and_more'),
        ('insurance', '0006_hmocoverageplanmodel_admission_annual_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_covered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_patient_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_approved_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved')], default='pending', max_length=20)),
                ('claim_type', models.CharField(default='mixed', help_text='Type of claims: drug, lab, scan, surgery, or mixed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_summaries', to='inpatient.admission')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_summaries', to='consultation.consultationsessionmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claim_summaries', to=settings.AUTH_USER_MODEL)),
                ('patient_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_summaries', to='insurance.patientinsurancemodel')),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_summaries', to='inpatient.surgery')),
            ],
            options={
                'verbose_name_plural': 'Insurance Claim Summaries',
                'ordering': ['-last_updated_at'],
            },
        ),
        migrations.AddField(
            model_name='insuranceclaimmodel',
            name='claim_summary',
            field=models.ForeignKey(blank=True, help_text='Groups related claims together', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insuranceclaimsummary'),
        ),
    ]
