# Generated by Django 5.0 on 2025-09-28 05:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard'), ('electric', 'Electric'), ('icu', 'ICU Bed'), ('isolation', 'Isolation'), ('bariatric', 'Bariatric')], default='standard', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Being Cleaned')], default='available', max_length=20)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override ward rate if different', max_digits=10, null=True)),
                ('features', models.TextField(blank=True, help_text='Special features (e.g., oxygen outlet, monitor, etc.)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ward__name', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='InpatientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_billing_for_admission', models.CharField(choices=[('free', 'Free'), ('daily', 'Daily Charge'), ('one_time', 'One-time Charge')], default='free', help_text='How are beds billed for regular admissions?', max_length=20)),
                ('bed_billing_for_surgery', models.CharField(choices=[('free', 'Free'), ('daily', 'Daily Charge'), ('one_time', 'One-time Charge')], default='daily', help_text='How are beds billed for surgery patients?', max_length=20)),
                ('admission_billing_type', models.CharField(choices=[('none', 'No Admission Fee'), ('one_time', 'One-time Fee'), ('daily', 'Daily Fee')], default='one_time', help_text='Type of admission billing', max_length=20)),
                ('admission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Admission fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('surgery_billing_type', models.CharField(choices=[('none', 'No Surgery Fee'), ('one_time', 'One-time Fee'), ('daily', 'Daily Fee')], default='one_time', help_text='Type of surgery facility billing', max_length=20)),
                ('surgery_amount', models.DecimalField(decimal_places=2, default=0, help_text='Surgery facility fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bed_daily_cost', models.DecimalField(decimal_places=2, default=0, help_text='Daily bed cost when charged', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('compile_surgery_drugs', models.BooleanField(default=True, help_text='Automatically include drugs from surgery packages?')),
                ('compile_surgery_labs', models.BooleanField(default=True, help_text='Automatically include lab tests from surgery packages?')),
                ('compile_surgery_scans', models.BooleanField(default=True, help_text='Automatically include scans from surgery packages?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inpatient Settings',
                'verbose_name_plural': 'Inpatient Settings',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_number', models.CharField(max_length=50, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('pre_op_diagnosis', models.TextField()),
                ('post_op_diagnosis', models.TextField(blank=True, null=True)),
                ('procedure_notes', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('custom_surgeon_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Override surgeon fee if different', max_digits=10, null=True)),
                ('custom_anesthesia_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Override anesthesia fee if different', max_digits=10, null=True)),
                ('custom_facility_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Override facility fee if different', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Surgeries',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_optional', models.BooleanField(default=False)),
                ('timing', models.CharField(blank=True, help_text="e.g., 'Pre-op', 'Post-op', 'During surgery'", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False)),
                ('timing', models.CharField(blank=True, help_text="e.g., 'Pre-op', 'Post-op', 'Day 1'", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False)),
                ('timing', models.CharField(blank=True, help_text="e.g., 'Pre-op', 'Intra-op', 'Follow-up'", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General Surgery'), ('orthopedic', 'Orthopedic'), ('cardiac', 'Cardiac'), ('neurological', 'Neurological'), ('gynecological', 'Gynecological'), ('urological', 'Urological'), ('ophthalmic', 'Ophthalmic'), ('ent', 'ENT'), ('plastic', 'Plastic Surgery'), ('emergency', 'Emergency Surgery')], max_length=50)),
                ('base_surgeon_fee', models.DecimalField(decimal_places=2, help_text='Base surgeon fee for this surgery type', max_digits=10)),
                ('base_anesthesia_fee', models.DecimalField(decimal_places=2, default=0, help_text='Base anesthesia fee', max_digits=10)),
                ('base_facility_fee', models.DecimalField(decimal_places=2, default=0, help_text='Base facility/theater fee', max_digits=10)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated surgery duration in hours', max_digits=4, null=True)),
                ('requires_icu', models.BooleanField(default=False, help_text='Does this surgery typically require ICU?')),
                ('typical_stay_days', models.PositiveIntegerField(blank=True, help_text='Typical hospital stay in days', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Surgery Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ward_type', models.CharField(choices=[('general', 'General Ward'), ('private', 'Private Ward'), ('icu', 'ICU'), ('surgery', 'Surgery Ward'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of beds')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergency'), ('elective', 'Elective'), ('transfer', 'Transfer'), ('readmission', 'Readmission')], default='elective', max_length=20)),
                ('chief_complaint', models.TextField()),
                ('admission_diagnosis', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('absconded', 'Absconded')], default='active', max_length=20)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('admission_fee_charged', models.DecimalField(blank=True, decimal_places=2, help_text='The admission fee charged at the time of admission.', max_digits=10, null=True)),
                ('bed_fee_charged', models.DecimalField(blank=True, decimal_places=2, help_text='The daily or one-time bed fee charged.', max_digits=10, null=True)),
                ('admission_notes', models.TextField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
    ]
