# Generated by Django 5.0 on 2025-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inpatient', '0001_initial'),
        ('laboratory', '0002_initial'),
        ('patient', '0002_initial'),
        ('pharmacy', '0001_initial'),
        ('scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='inpatient.bed'),
        ),
        migrations.AddField(
            model_name='inpatientsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Associated admission if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='anesthesiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_surgeries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='assistant_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_surgeries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='primary_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_surgeries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgerydrug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel'),
        ),
        migrations.AddField(
            model_name='surgerylab',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtesttemplatemodel'),
        ),
        migrations.AddField(
            model_name='surgeryscan',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.scantemplatemodel'),
        ),
        migrations.AddField(
            model_name='surgerytype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgeryscan',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatient.surgerytype'),
        ),
        migrations.AddField(
            model_name='surgerylab',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatient.surgerytype'),
        ),
        migrations.AddField(
            model_name='surgerydrug',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatient.surgerytype'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatient.surgerytype'),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inpatient.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
