# Generated by Django 5.0 on 2025-11-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_diagnosisoption_options_and_more'),
        ('inpatient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Medical specialization performing this surgery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='consultation.specializationmodel'),
        ),
        migrations.AddField(
            model_name='surgerytype',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Medical specialization that performs this surgery type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_types', to='consultation.specializationmodel'),
        ),
    ]
