# Generated by Django 5.0 on 2025-09-07 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_alter_bed_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='patientModel',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='patientModel',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='surgery',
            name='primary_surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_surgeries', to=settings.AUTH_USER_MODEL),
        ),
    ]
