# Generated by Django 5.0 on 2025-11-23 10:14

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_surgery_specialization_surgerytype_specialization'),
        ('pharmacy', '0003_drugordermodel_first_dose_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='admission_fee_charged',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bed_fee_charged',
        ),
        migrations.AddField(
            model_name='admission',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current deposit balance remaining', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_consultation_fee_date',
            field=models.DateField(blank=True, help_text='Date of last consultation fee charged', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_consultation_fee_valid_until',
            field=models.DateField(blank=True, help_text='Date until which last consultation fee is valid', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running total of all services charged', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid (deposits + direct payments)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inpatientsettings',
            name='admission_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time admission fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inpatientsettings',
            name='charge_admission_fee',
            field=models.BooleanField(default=False, help_text='Charge one-time admission fee when patient is admitted?'),
        ),
        migrations.AddField(
            model_name='inpatientsettings',
            name='default_max_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Default maximum debt allowed per admission', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_type',
            field=models.CharField(blank=True, default='elective', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AdmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of admission type (e.g., General Ward, ICU, Private Suite)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this admission type includes', null=True)),
                ('bed_daily_fee', models.DecimalField(decimal_places=2, help_text='Daily bed charge for this admission type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Consultation fee charged per ward round', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_fee_duration_days', models.PositiveIntegerField(default=1, help_text='How many days one consultation fee covers (e.g., 3 = fee covers 3 days)', validators=[django.core.validators.MinValueValidator(1)])),
                ('requires_deposit', models.BooleanField(default=True, help_text='Does this admission type require an initial deposit?')),
                ('minimum_deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Minimum deposit required for admission', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_debt_allowed', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Maximum debt allowed before services are blocked', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Type',
                'verbose_name_plural': 'Admission Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WardRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.CharField(blank=True, help_text='Auto-generated unique round number', max_length=50, unique=True)),
                ('round_date', models.DateField(default=datetime.date.today, help_text='Date of the ward round')),
                ('round_time', models.TimeField(auto_now_add=True, help_text='Time when ward round started')),
                ('vitals', models.JSONField(blank=True, help_text='\n        Patient vitals recorded during this round.\n        Example: {"bp": "120/80", "temp": 37.2, "pulse": 72, "spo2": 98, "weight": 70}\n        ', null=True)),
                ('chief_complaint', models.TextField(blank=True, help_text="Patient's current complaints or concerns")),
                ('assessment', models.TextField(blank=True, help_text="Doctor's clinical assessment and findings")),
                ('plan', models.TextField(blank=True, help_text='Treatment plan and next steps')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='in_progress', max_length=20)),
                ('consultation_fee_charged', models.DecimalField(blank=True, decimal_places=2, help_text='Consultation fee charged during this ward round (if any)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the ward round was completed', null=True)),
                ('admission', models.ForeignKey(help_text='The admission this ward round belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ward_rounds', to='inpatient.admission')),
                ('doctor', models.ForeignKey(help_text='Doctor conducting this ward round', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_rounds_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ward Round',
                'verbose_name_plural': 'Ward Rounds',
                'ordering': ['-round_date', '-round_time'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('drug', 'Drug Administration'), ('vitals', 'Vital Signs Check'), ('lab', 'Lab Sample Collection'), ('scan', 'Imaging Appointment'), ('wound_care', 'Wound Care'), ('feeding', 'Feeding/Nutrition'), ('physiotherapy', 'Physiotherapy'), ('other', 'Other')], help_text='Type of task to be performed', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of what needs to be done')),
                ('scheduled_datetime', models.DateTimeField(help_text='When this task should be performed')),
                ('completed_datetime', models.DateTimeField(blank=True, help_text='When the task was actually completed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or special considerations')),
                ('completion_notes', models.TextField(blank=True, help_text='Notes recorded when task was completed')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this part of a recurring task series?')),
                ('recurrence_pattern', models.CharField(blank=True, help_text='Frequency pattern: OD, BD, TDS, QDS, Q4H, Q6H, etc.', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(help_text='The admission this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inpatient.admission')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to perform this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admission_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Staff member who completed this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_admission_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_tasks', to=settings.AUTH_USER_MODEL)),
                ('drug_order', models.ForeignKey(blank=True, help_text="Drug order this task is for (if task_type is 'drug')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_tasks', to='pharmacy.drugordermodel')),
                ('parent_task', models.ForeignKey(blank=True, help_text='Parent task if this is part of a recurring series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='inpatient.admissiontask')),
            ],
            options={
                'verbose_name': 'Admission Task',
                'verbose_name_plural': 'Admission Tasks',
                'ordering': ['scheduled_datetime', 'priority'],
                'indexes': [models.Index(fields=['admission', 'status'], name='inpatient_a_admissi_bbcb22_idx'), models.Index(fields=['scheduled_datetime'], name='inpatient_a_schedul_5091bd_idx'), models.Index(fields=['status', 'scheduled_datetime'], name='inpatient_a_status_03f482_idx')],
            },
        ),
    ]
