# Generated by Django 5.0 on 2025-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_rename_patientmodel_admission_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_fee_charged',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The admission fee charged at the time of admission.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='bed_fee_charged',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The daily or one-time bed fee charged.', max_digits=10, null=True),
        ),
    ]
