# Generated by Django 5.0 on 2025-11-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_remove_admission_admission_fee_charged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_type',
            field=models.ForeignKey(help_text='Type of admission (General Ward, ICU, Private, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='inpatient.admissiontype'),
        ),
    ]
