# Generated by Django 5.0 on 2025-11-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_patienttransactionmodel_ward_round'),
        ('inpatient', '0005_alter_admission_admission_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WardRound',
        ),
    ]
