# Generated by Django 5.0 on 2026-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0006_delete_wardround'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_activated_date',
            field=models.DateTimeField(blank=True, help_text='Date when admission was confirmed and billing started', null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('absconded', 'Absconded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned')], default='available', max_length=20),
        ),
    ]
