# Generated by Django 6.0.2 on 2026-03-03 07:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0007_admission_admission_activated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='attending_doctor',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='expected_discharge_date',
        ),
        migrations.RemoveField(
            model_name='inpatientsettings',
            name='admission_fee_amount',
        ),
        migrations.RemoveField(
            model_name='inpatientsettings',
            name='charge_admission_fee',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_fee_charged',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time admission fee charged at confirmation', max_digits=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='bed_rate_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bed rate snapshotted at confirmation time', max_digits=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='consultation_fee_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Consultation fee rate snapshotted at confirmation time', max_digits=10),
        ),
    ]
