# Generated by Django 6.0.2 on 2026-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0008_remove_admission_attending_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontask',
            name='task_type',
            field=models.CharField(choices=[('drug', 'Drug Administration'), ('vitals', 'Vital Signs Check'), ('lab', 'Lab Sample Collection'), ('scan', 'Imaging Appointment'), ('wound_care', 'Wound Care'), ('feeding', 'Feeding/Nutrition'), ('physiotherapy', 'Physiotherapy'), ('vitals', 'Vitals'), ('ward_round', 'Ward Round'), ('general', 'General'), ('other', 'Other')], help_text='Type of task to be performed', max_length=20),
        ),
    ]
