# Generated by Django 6.0.2 on 2026-05-13 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0009_alter_admissiontask_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiontask',
            options={'ordering': ['scheduled_datetime', 'priority'], 'permissions': [('get_task_notification', 'Receives real-time admission task notifications')], 'verbose_name': 'Admission Task', 'verbose_name_plural': 'Admission Tasks'},
        ),
        migrations.AddField(
            model_name='admission',
            name='condition',
            field=models.CharField(choices=[('stable', 'Stable'), ('critical', 'Critical'), ('serious', 'Serious'), ('recovering', 'Recovering'), ('healthy', 'Healthy — Ready for Discharge')], default='stable', help_text='Current clinical condition of the patient', max_length=20),
        ),
        migrations.CreateModel(
            name='HandoverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('snapshot', models.JSONField(blank=True, help_text='Auto-captured census at time of handover submission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handover Note',
                'verbose_name_plural': 'Handover Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('general', 'General Note'), ('patient', 'Patient Specific')], default='general', max_length=20)),
                ('note', models.TextField(help_text='TinyMCE rich text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_entries', to='inpatient.admission')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inpatient.handovernote')),
            ],
            options={
                'verbose_name': 'Handover Entry',
                'ordering': ['created_at'],
            },
        ),
    ]
