# Generated by Django 5.0 on 2025-09-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HODModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('next', 'NEXT'), ('past', 'PAST')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_staff_id', models.BooleanField(default=True)),
                ('staff_prefix', models.CharField(blank=True, default='stf', max_length=10, null=True)),
                ('use_dept_prefix_for_id', models.BooleanField(default=False)),
                ('allow_profile_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_login', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('document_type', models.CharField(choices=[('Certificate', 'Certificate'), ('Licence', 'Licence'), ('others', 'OTHERS')], max_length=50)),
                ('document', models.FileField(upload_to='staff/document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffIDGeneratorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_id', models.BigIntegerField(default=0)),
                ('last_staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual'), ('Casual', 'Casual'), ('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Compassionate', 'Compassionate'), ('Unpaid', 'Unpaid'), ('others', 'OTHERS')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('applied_days', models.PositiveIntegerField()),
                ('approved_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('declined', 'DECLINED')], default='pending', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/staff')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'SINGLE'), ('married', 'MARRIED'), ('widowed', 'WIDOWED'), ('divorced', 'DIVORCED')], max_length=30, null=True)),
                ('religion', models.CharField(blank=True, choices=[('christianity', 'CHRISTIANITY'), ('islam', 'ISLAM'), ('others', 'OTHERS')], max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='staff/cv')),
                ('contract_type', models.CharField(choices=[('full time', 'FULL TIME'), ('part time', 'PART TIME'), ('internship', 'INTERNSHIP'), ('it', 'IT'), ('nysc', 'NYSC'), ('probation', 'PROBATION')], max_length=50)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('contract_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=50)),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=20, null=True)),
                ('genotype', models.CharField(blank=True, choices=[('aa', 'AA'), ('as', 'AS'), ('ac', 'AC'), ('ss', 'SS')], max_length=20, null=True)),
                ('health_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('suspended', 'SUSPENDED'), ('retired', 'RETIRED')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_dept_name_combo'),
        ),
        migrations.AddField(
            model_name='hodmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.departmentmodel'),
        ),
        migrations.AddField(
            model_name='positionmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='human_resource.departmentmodel'),
        ),
        migrations.AddField(
            model_name='staffdocumentmodel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_doc_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='staffidgeneratormodel',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='single_generator_record'),
        ),
        migrations.AddField(
            model_name='staffleavemodel',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_appliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleavemodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_staffs', to='human_resource.departmentmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_staffs', to='human_resource.positionmodel'),
        ),
        migrations.AddField(
            model_name='staffleavemodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffdocumentmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='hodmodel',
            name='deputy_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_hod', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='hodmodel',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffprofilemodel',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffprofilemodel',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='positionmodel',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='unique_name_and_dept_combo'),
        ),
    ]
