# Generated by Django 5.0 on 2025-08-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_receipt_format', models.CharField(blank=True, choices=[('portrait', 'PORTRAIT'), ('landscape', 'LANDSCAPE')], max_length=50, null=True)),
                ('receipt_signature', models.FileField(blank=True, null=True, upload_to='finance/setting/receipt')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
