# Generated by Django 5.0 on 2025-09-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('human_resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.departmentmodel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategory'),
        ),
        migrations.AddField(
            model_name='income',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.departmentmodel'),
        ),
        migrations.AddField(
            model_name='income',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incomecategory'),
        ),
        migrations.AddField(
            model_name='moneyremittance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittances_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneyremittance',
            name='remitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherpaymentservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
