# Generated by Django 5.0 on 2025-08-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationPaymentModel',
        ),
    ]
