# Generated by Django 5.0 on 2025-09-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('finance', '0002_initial'),
        ('human_resource', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('laboratory', '0002_initial'),
        ('patient', '0002_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrefundmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultationfeemodel'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='lab_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labtestordermodel'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='other_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.otherpaymentservice'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.moneyremittance'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.patientservicetransaction'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatient.surgery'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffbankdetail',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='walletwithdrawalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='walletwithdrawalrecord',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Link to the corresponding OUT transaction record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.patienttransactionmodel'),
        ),
        migrations.AddField(
            model_name='walletwithdrawalrecord',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_withdrawals_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patienttransactionmodel',
            index=models.Index(fields=['patient', 'transaction_type'], name='finance_pat_patient_5c29f7_idx'),
        ),
        migrations.AddIndex(
            model_name='patienttransactionmodel',
            index=models.Index(fields=['date'], name='finance_pat_date_a7f767_idx'),
        ),
        migrations.AddIndex(
            model_name='patienttransactionmodel',
            index=models.Index(fields=['status'], name='finance_pat_status_e9c11f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('staff', 'month', 'year')},
        ),
    ]
