# Generated by Django 5.0 on 2025-10-13 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('finance', '0004_alter_patienttransactionmodel_amount_and_more'),
        ('inpatient', '0002_initial'),
        ('laboratory', '0003_externallabtestorder'),
        ('patient', '0002_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='direct_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid directly (cash/card/transfer) for this transaction', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='Links child transactions to parent payment transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_transactions', to='finance.patienttransactionmodel'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted from wallet for this transaction (for mixed payments)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('wallet_funding', 'WALLET FUNDING'), ('consultation_payment', 'CONSULTATION PAYMENT'), ('drug_payment', 'DRUG PAYMENT'), ('lab_payment', 'LAB PAYMENT'), ('scan_payment', 'SCAN PAYMENT'), ('admission_payment', 'ADMISSION PAYMENT'), ('surgery_payment', 'SURGERY PAYMENT'), ('service', 'SERVICE'), ('item', 'ITEM PURCHASE'), ('other_payment', 'OTHER PAYMENT'), ('drug_refund', 'DRUG REFUND'), ('lab_refund', 'LAB REFUND'), ('scan_refund', 'SCAN REFUND'), ('admission_refund', 'ADMISSION REFUND'), ('surgery_refund', 'SURGERY REFUND'), ('other_refund', 'OTHER REFUND'), ('wallet_withdrawal', 'WALLET WITHDRAWAL'), ('refund_to_wallet', 'REFUND TO WALLET'), ('wallet_correction', 'WALLET CORRECTION'), ('direct_payment', 'DIRECT PAYMENT')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='patienttransactionmodel',
            index=models.Index(fields=['parent_transaction'], name='finance_pat_parent__3611b4_idx'),
        ),
    ]
