# Generated by Django 5.0 on 2025-09-03 10:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_patienttransactionmodel_new_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettingmodel',
            name='minimum_funding',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
