# Generated by Django 5.0 on 2025-09-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_patientqueuemodel_payment_and_more'),
        ('finance', '0005_financesettingmodel_minimum_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='fee_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultationfeemodel'),
        ),
    ]
