# Generated by Django 5.0 on 2025-10-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_patienttransactionmodel_direct_payment_amount_and_more'),
        ('pharmacy', '0002_alter_drugmodel_brand_name_alter_drugmodel_sku'),
        ('scan', '0002_externalscanorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='drug_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pharmacy.drugordermodel'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='scan_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='scan.scanordermodel'),
        ),
    ]
