# Generated by Django 5.0 on 2025-09-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_patienttransactionmodel_fee_structure'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='lab_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labtestordermodel'),
        ),
    ]
