# Generated by Django 5.0 on 2025-11-04 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_patienttransactionmodel_drug_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienttransactionmodel',
            options={'ordering': ['-created_at'], 'permissions': [('view_staff_collections', 'Can view staff collection reports'), ('view_all_staff_collections', 'Can view all staff collections'), ('view_financial_reports', 'Can view financial reports'), ('view_staff_history', 'Can view staff transaction history')]},
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who paid this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('pos', 'POS/Card')], default='cash', help_text='Method used to pay this expense', max_length=20),
        ),
    ]
