# Generated by Django 5.0 on 2025-09-03 18:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_patienttransactionmodel_lab_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financesettingmodel',
            name='default_receipt_format',
        ),
        migrations.RemoveField(
            model_name='financesettingmodel',
            name='receipt_signature',
        ),
        migrations.AddField(
            model_name='financesettingmodel',
            name='allow_negative_balance',
            field=models.BooleanField(default=False, help_text='If True, patients can have a negative wallet balance (post-paid). If False, payments will fail if balance is insufficient.'),
        ),
        migrations.AddField(
            model_name='financesettingmodel',
            name='maximum_funding',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='The maximum amount a patient can fund their wallet with in one transaction.', max_digits=12),
        ),
    ]
