# Generated by Django 5.0 on 2025-11-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_patienttransactionmodel_options_and_more'),
        ('inpatient', '0004_remove_admission_admission_fee_charged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='ward_round',
            field=models.ForeignKey(blank=True, help_text='Link to ward round if this is a ward round consultation fee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inpatient.wardround'),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('wallet_funding', 'WALLET FUNDING'), ('consultation_payment', 'CONSULTATION PAYMENT'), ('drug_payment', 'DRUG PAYMENT'), ('lab_payment', 'LAB PAYMENT'), ('scan_payment', 'SCAN PAYMENT'), ('admission_payment', 'ADMISSION PAYMENT'), ('surgery_payment', 'SURGERY PAYMENT'), ('service', 'SERVICE'), ('item', 'ITEM PURCHASE'), ('other_payment', 'OTHER PAYMENT'), ('drug_refund', 'DRUG REFUND'), ('lab_refund', 'LAB REFUND'), ('scan_refund', 'SCAN REFUND'), ('admission_refund', 'ADMISSION REFUND'), ('surgery_refund', 'SURGERY REFUND'), ('other_refund', 'OTHER REFUND'), ('wallet_withdrawal', 'WALLET WITHDRAWAL'), ('refund_to_wallet', 'REFUND TO WALLET'), ('wallet_correction', 'WALLET CORRECTION'), ('direct_payment', 'DIRECT PAYMENT'), ('ward_round_payment', 'WARD ROUND PAYMENT')], max_length=20),
        ),
    ]
