# Generated by Django 5.0 on 2025-11-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_patienttransactionmodel_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttransactionmodel',
            name='ward_round',
        ),
    ]
