# Generated by Django 5.0 on 2025-09-05 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_quotation_document_alter_quotation_department_and_more'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.departmentmodel'),
        ),
    ]
