# Generated by Django 5.0 on 2025-11-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_patienttransactionmodel_ward_round'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='registration_payment',
            field=models.ForeignKey(blank=True, help_text='Links pre-registration transactions to registration payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='patient.registrationpaymentmodel'),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel'),
        ),
    ]
