# Generated by Django 5.0 on 2026-01-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_patienttransactionmodel_registration_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Name of walk-in customer (only used when patient is null)', max_length=200),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='source',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('admission', 'Admission'), ('walkin', 'Walk-in Sale'), ('other', 'Other')], default='other', help_text='Source of this transaction', max_length=20),
        ),
    ]
