# Generated by Django 5.0 on 2025-09-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_quotation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
