# Generated by Django 5.0 on 2026-01-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_patienttransactionmodel_lab_structure'),
        ('laboratory', '0006_labtestordermodel_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='lab_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='laboratory.labtestordermodel'),
        ),
    ]
