# Generated by Django 5.0 on 2025-09-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_quotation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='quotation',
        ),
    ]
