# Generated by Django 5.0 on 2025-09-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_expense_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
