# Generated by Django 5.0 on 2025-09-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_expense_expense_number'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbankdetail',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='human_resource.staffmodel'),
        ),
    ]
