# Generated by Django 5.0 on 2025-09-05 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_staffbankdetail_staff'),
        ('human_resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-year', '-month', 'staff__first_name']},
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='overtime',
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tracks the actual amount paid.', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g., salary advance, loan repayment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Any additional bonus for this month.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='notes',
            field=models.CharField(blank=True, help_text='Optional notes for this payslip.', max_length=255),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='pension_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='human_resource.staffmodel'),
        ),
    ]
