# Generated by Django 5.0 on 2025-09-05 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_salaryrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remittance_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_cash_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transfer_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_remitted_cash', models.DecimalField(decimal_places=2, help_text='The actual amount of cash being handed over.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISCREPANCY', 'Discrepancy Noted')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes explaining any discrepancy or details about the remittance.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittances_approved', to=settings.AUTH_USER_MODEL)),
                ('remitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.moneyremittance'),
        ),
    ]
