# Generated by Django 5.0 on 2025-09-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_moneyremittance_patienttransactionmodel_remittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
