# Generated by Django 5.0 on 2025-09-07 15:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_remove_quotationitem_quotation_delete_quotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('medical_services', 'Medical Services'), ('diagnostic_services', 'Diagnostic Services'), ('documents', 'Medical Documents'), ('equipment_rental', 'Equipment Rental'), ('facility_services', 'Facility Services'), ('professional_fees', 'Professional Fees'), ('other', 'Other')], max_length=50)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Default amount (can be overridden during payment)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_fixed_amount', models.BooleanField(default=False, help_text='If true, amount cannot be changed during payment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
