# Generated by Django 5.0 on 2025-09-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_diagnosisoption_and_more'),
        ('finance', '0020_otherpaymentservice'),
        ('inpatient', '0001_initial'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatient.surgery'),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultationfeemodel'),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='lab_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labtestordermodel'),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('wallet_funding', 'WALLET FUNDING'), ('consultation_payment', 'CONSULTATION PAYMENT'), ('drug_payment', 'DRUG PAYMENT'), ('lab_payment', 'LAB PAYMENT'), ('scan_payment', 'SCAN PAYMENT'), ('admission_payment', 'ADMISSION PAYMENT'), ('surgery_payment', 'SURGERY PAYMENT'), ('other_payment', 'OTHER PAYMENT'), ('drug_refund', 'DRUG REFUND'), ('lab_refund', 'LAB REFUND'), ('scan_refund', 'SCAN REFUND'), ('admission_refund', 'ADMISSION REFUND'), ('surgery_refund', 'SURGERY REFUND'), ('other_refund', 'OTHER REFUND'), ('wallet_withdrawal', 'WALLET WITHDRAWAL')], max_length=20),
        ),
        migrations.AddField(
            model_name='otherpaymentservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='other_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.otherpaymentservice'),
        ),
    ]
