# Generated by Django 5.0 on 2025-09-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_patienttransactionmodel_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='valid_till',
            field=models.DateField(blank=True, help_text='The date until which the paid service is valid (e.g., for consultations).', null=True),
        ),
    ]
