# Generated by Django 5.0 on 2025-09-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_patienttransactionmodel_valid_till'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.serviceitem'),
        ),
        migrations.AddField(
            model_name='patienttransactionmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service'),
        ),
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('wallet_funding', 'WALLET FUNDING'), ('consultation_payment', 'CONSULTATION PAYMENT'), ('drug_payment', 'DRUG PAYMENT'), ('lab_payment', 'LAB PAYMENT'), ('scan_payment', 'SCAN PAYMENT'), ('admission_payment', 'ADMISSION PAYMENT'), ('surgery_payment', 'SURGERY PAYMENT'), ('service', 'SERVICE'), ('item', 'ITEM PURCHASE'), ('other_payment', 'OTHER PAYMENT'), ('drug_refund', 'DRUG REFUND'), ('lab_refund', 'LAB REFUND'), ('scan_refund', 'SCAN REFUND'), ('admission_refund', 'ADMISSION REFUND'), ('surgery_refund', 'SURGERY REFUND'), ('other_refund', 'OTHER REFUND'), ('wallet_withdrawal', 'WALLET WITHDRAWAL')], max_length=20),
        ),
    ]
