# Generated by Django 5.0 on 2025-09-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_patienttransactionmodel_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttransactionmodel',
            name='item',
        ),
    ]
