# Generated by Django 5.0 on 2025-09-15 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_remove_patienttransactionmodel_item'),
        ('service', '0002_remove_service_created_by_remove_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttransactionmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.patientservicetransaction'),
        ),
    ]
