# Generated by Django 5.0 on 2025-09-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_patienttransactionmodel_service'),
        ('patient', '0002_alter_patientmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRefundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
            ],
        ),
    ]
