# Generated by Django 5.0 on 2025-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestordermodel',
            name='source',
            field=models.CharField(choices=[('doctor', 'Doctor Prescribed'), ('lab', 'Lab Direct Order')], default='lab', help_text='Source of the test order', max_length=20),
        ),
    ]
