# Generated by Django 5.0 on 2025-09-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestordermodel',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_consultation_order', to='consultation.consultationsessionmodel'),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='payment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='sample_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='surgery',
            field=models.ForeignKey(blank=True, help_text='Link to a surgery record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_orders', to='inpatient.surgery'),
        ),
        migrations.AddField(
            model_name='labtestresultmodel',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labtestordermodel'),
        ),
        migrations.AddField(
            model_name='labtestresultmodel',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtesttemplatebuildermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestcategorymodel'),
        ),
        migrations.AddField(
            model_name='labtesttemplatemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='laboratory.labtestcategorymodel'),
        ),
        migrations.AddField(
            model_name='labtesttemplatebuildermodel',
            name='created_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtesttemplatemodel'),
        ),
        migrations.AddField(
            model_name='labtestordermodel',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='laboratory.labtesttemplatemodel'),
        ),
        migrations.AddField(
            model_name='labreagentmodel',
            name='used_in_templates',
            field=models.ManyToManyField(blank=True, related_name='reagents', to='laboratory.labtesttemplatemodel'),
        ),
        migrations.AddField(
            model_name='labequipmentmodel',
            name='supported_templates',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='laboratory.labtesttemplatemodel'),
        ),
    ]
