# Generated by Django 5.0 on 2025-10-01 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('laboratory', '0002_initial'),
        ('patient', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLabTestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(blank=True, max_length=20)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('special_instructions', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, help_text='Upload external lab report (PDF/Image)', null=True, upload_to='external_lab_results/%Y/%m/')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('result_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_lab_orders', to='consultation.consultationsessionmodel')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_external_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lab_orders', to='patient.patientmodel')),
                ('result_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_external_lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Lab Test Order',
                'verbose_name_plural': 'External Lab Test Orders',
                'db_table': 'external_lab_test_orders',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
