# Generated by Django 5.0 on 2025-09-08 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labtestordermodel_admission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labsettingmodel',
            options={'verbose_name_plural': 'Laboratory Settings'},
        ),
        migrations.RemoveField(
            model_name='labsettingmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='labsettingmodel',
            name='lab_license',
        ),
        migrations.AddField(
            model_name='labsettingmodel',
            name='allow_direct_lab_order',
            field=models.BooleanField(default=False, help_text='Allow patients to order lab tests directly without a consultation (walk-in).'),
        ),
        migrations.AddField(
            model_name='labsettingmodel',
            name='allow_result_print_in_lab',
            field=models.BooleanField(default=True, help_text='Allow staff in the laboratory department to print test results.'),
        ),
        migrations.AddField(
            model_name='labsettingmodel',
            name='allow_result_printing_by_consultant',
            field=models.BooleanField(default=True, help_text='Allow the ordering consultant/doctor to print test results from their dashboard.'),
        ),
        migrations.AddField(
            model_name='labsettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labsettingmodel',
            name='lab_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterModelTable(
            name='labsettingmodel',
            table=None,
        ),
    ]
