# Generated by Django 5.0 on 2025-08-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labtestordermodel_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestordermodel',
            name='payment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestordermodel',
            name='payment_status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='labtestordermodel',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestordermodel',
            name='sample_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Awaiting Sample'), ('collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
