# Generated by Django 5.0 on 2025-09-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_labsettingmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettingmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labsettingmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
