# Generated by Django 5.0 on 2025-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_externallabtestorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtestordermodel',
            options={'ordering': ['-ordered_at'], 'permissions': [('view_financial_report', 'Can view financial reports')]},
        ),
    ]
