# Generated by Django 5.0 on 2025-09-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_rename_consultation_notes_consultationsessionmodel_assessment'),
        ('laboratory', '0004_labsettingmodel_email_labsettingmodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestordermodel',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_consultation_order', to='consultation.consultationsessionmodel'),
        ),
    ]
