# Generated by Django 5.0 on 2025-09-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labtestordermodel_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttemplatemodel',
            name='reason_for_deactivate',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
