# Generated by Django 5.0 on 2025-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_labtesttemplatemodel_reason_for_deactivate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtestresultmodel',
            options={'permissions': [('can_verify_lab_result', 'Can verify lab test result')]},
        ),
    ]
