# Generated by Django 5.0 on 2025-08-25 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drug_batches',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DrugCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Drug Categories',
                'db_table': 'drug_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugFormulationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('injection', 'Injection'), ('syrup', 'Syrup'), ('cream', 'Cream'), ('drops', 'Drops')], max_length=20)),
                ('strength', models.CharField(help_text='e.g., 500mg, 250mg/5ml', max_length=50)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drug_formulations',
                'ordering': ['generic_drug__generic_name', 'form_type'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drug_manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_sale_without_prescription', models.BooleanField(default=False)),
                ('auto_transfer_threshold', models.IntegerField(default=5, help_text='Auto-suggest transfer when pharmacy stock is below this level')),
            ],
            options={
                'db_table': 'pharmacy_settings',
            },
        ),
        migrations.CreateModel(
            name='DrugImportLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to='drug_imports/')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drug_import_logs',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='DrugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, help_text='Commercial/Brand name', max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('store_quantity', models.FloatField(default=0, help_text='Quantity in store/warehouse')),
                ('pharmacy_quantity', models.FloatField(default=0, help_text='Quantity in pharmacy counter')),
                ('minimum_stock_level', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pharmacy.drugformulationmodel')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pharmacy.manufacturermodel')),
            ],
            options={
                'db_table': 'drugs',
                'ordering': ['formulation__generic_drug__generic_name', 'brand_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.FloatField()),
                ('quantity_left', models.FloatField(blank=True, default=0)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_worth', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('location', models.CharField(choices=[('store', 'Store/Warehouse'), ('pharmacy', 'Pharmacy Counter')], default='store', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('damaged', 'Damaged')], default='active', max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugbatchmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='pharmacy.drugmodel')),
            ],
            options={
                'db_table': 'drug_stocks',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='DrugStockOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('expired', 'Expired'), ('damaged', 'Damaged/Spoilt'), ('transfer', 'Transfer (Store to Pharmacy)'), ('return', 'Return to Supplier'), ('other', 'Other')], default='sale', max_length=20)),
                ('worth', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='pharmacy.drugstockmodel')),
            ],
            options={
                'db_table': 'drug_stock_outs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Paracetamol Variants')", max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('is_prescription', models.BooleanField(default=True)),
                ('drug_combinations', models.JSONField(default=list, help_text='\n        Array of specific combinations like:\n        [\n            {"strength": "500mg", "form": "tablet", "manufacturer": "GSK"},\n            {"strength": "250mg", "form": "syrup", "manufacturer": "Emzor"},\n            {"strength": "500mg", "form": "tablet", "manufacturer": "Bond"}\n        ]\n        ')),
                ('is_processed', models.BooleanField(default=False, help_text='Has this template been used to create drugs?')),
                ('drugs_created_count', models.IntegerField(default=0, help_text='Number of drug variants created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugcategorymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drug_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='pharmacy.drugmodel')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drug_transfers',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='GenericDrugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(help_text='WHO/INN generic name', max_length=200, unique=True)),
                ('atc_code', models.CharField(blank=True, help_text='WHO ATC code (e.g., N02BE01 for Paracetamol)', max_length=10)),
                ('is_prescription_only', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_drugs', to='pharmacy.drugcategorymodel')),
            ],
            options={
                'db_table': 'generic_drugs',
                'ordering': ['generic_name'],
            },
        ),
        migrations.AddField(
            model_name='drugformulationmodel',
            name='generic_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='pharmacy.genericdrugmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='drugformulationmodel',
            unique_together={('generic_drug', 'form_type', 'strength')},
        ),
    ]
