# Generated by Django 5.0 on 2025-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmodel',
            name='brand_name',
            field=models.CharField(blank=True, default='', help_text='Commercial/Brand name', max_length=200),
        ),
        migrations.AlterField(
            model_name='drugmodel',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Stock Keeping Unit', max_length=100),
        ),
    ]
