# Generated by Django 5.0 on 2025-08-26 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstockmodel',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pharmacy.drugbatchmodel'),
        ),
        migrations.AlterField(
            model_name='drugstockoutmodel',
            name='reason',
            field=models.CharField(choices=[('sale', 'Sale'), ('expired', 'Expired'), ('damaged', 'Damaged/Spoilt'), ('return', 'Return to Supplier'), ('other', 'Other')], default='sale', max_length=20),
        ),
    ]
