# Generated by Django 5.0 on 2025-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_drugstockmodel_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstockoutmodel',
            name='worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
