# Generated by Django 5.0 on 2025-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_drugmodel_brand_name_alter_drugmodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugordermodel',
            name='first_dose_time',
            field=models.TimeField(blank=True, help_text='Time for first dose (e.g., 08:00 AM) - used for task generation', null=True),
        ),
        migrations.AddField(
            model_name='drugordermodel',
            name='generate_tasks',
            field=models.BooleanField(default=False, help_text='Auto-generate administration tasks for this drug?'),
        ),
        migrations.AddField(
            model_name='drugordermodel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('wallet', 'Patient Wallet'), ('admission', 'Admission Deposit'), ('insurance', 'Insurance')], default='cash', max_length=20),
        ),
    ]
