# Generated by Django 5.0 on 2026-01-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_registrationpaymentmodel_status'),
        ('pharmacy', '0003_drugordermodel_first_dose_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugordermodel',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Name of walk-in customer (only used when patient is null)', max_length=200),
        ),
        migrations.AddField(
            model_name='drugordermodel',
            name='source',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('admission', 'Admission'), ('walkin', 'Walk-in Sale')], default='walkin', help_text='Source of this drug order', max_length=20),
        ),
        migrations.AlterField(
            model_name='drugordermodel',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='The patient for whom the drug is ordered (null for walk-ins).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_prescriptions', to='patient.patientmodel'),
        ),
    ]
