# Generated by Django 5.0 on 2025-09-17 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_allergy'),
        ('inpatient', '0003_rename_patientmodel_admission_patient_and_more'),
        ('patient', '0001_initial'),
        ('pharmacy', '0003_drugordermodel_consultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmodel',
            name='pack_size',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of units in a single sellable pack (e.g., 12 tablets per card).', null=True),
        ),
        migrations.CreateModel(
            name='ExternalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(help_text='Name of the prescribed drug not in inventory.', max_length=255)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(help_text="Manually entered quantity (e.g., '1 Bottle', '2 Packs').", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_prescriptions', to='inpatient.admission')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_prescriptions', to='consultation.consultationsessionmodel')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_external_drugs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_prescriptions', to='patient.patientmodel')),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_prescriptions', to='inpatient.surgery')),
            ],
            options={
                'verbose_name': 'External Prescription',
                'verbose_name_plural': 'External Prescriptions',
                'db_table': 'external_prescriptions',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
