# Generated by Django 5.0 on 2025-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_drugmodel_pack_size_externalprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstockmodel',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
