# Generated by Django 5.0 on 2025-09-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_drugstockmodel_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pharmacy.manufacturermodel'),
        ),
    ]
