# Generated by Django 5.0 on 2025-09-15 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_patientvitalsmodel_extra_note'),
        ('inpatient', '0003_rename_patientmodel_admission_patient_and_more'),
        ('patient', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='serviceitem',
            unique_together={('category', 'name')},
        ),
        migrations.RemoveField(
            model_name='serviceitemstockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceitemstockmovement',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='serviceresult',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='serviceresult',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='service',
            name='has_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='result_template',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='show_as_record_column',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='unit_of_measure',
            field=models.CharField(choices=[('piece', 'Piece'), ('pair', 'Pair'), ('box', 'Box'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('kg', 'Kilogram')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceitemstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('adjustment', 'Stock Adjustment'), ('sale', 'Sale to Patient'), ('return', 'Return from Patient'), ('expired', 'Expired/Damaged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceitemstockmovement',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitemstockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase Order'), ('sale', 'Patient Sale'), ('adjustment', 'Stock Adjustment'), ('sale_reversal', 'Sale Reversal'), ('expiry', 'Expiry/Damage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitemstockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceresult',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='service_results/'),
        ),
        migrations.CreateModel(
            name='PatientServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, help_text='Link to an admission record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_drug_orders', to='inpatient.admission')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_drug_consultation_order', to='consultation.consultationsessionmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='service.service')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='service.serviceitem')),
                ('surgery', models.ForeignKey(blank=True, help_text='Link to a surgery record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_drug_orders', to='inpatient.surgery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='serviceresult',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='service.patientservicetransaction'),
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='is_prescription_required',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='PatientModelServiceTransaction',
        ),
    ]
