# Generated by Django 5.0 on 2025-11-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_diagnosisoption_options_and_more'),
        ('service', '0002_serviceresult_is_verified_serviceresult_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='specializations',
            field=models.ManyToManyField(blank=True, help_text='Specializations this category belongs to (leave empty for general categories)', related_name='service_categories', to='consultation.specializationmodel'),
        ),
    ]
