# Generated by Django 5.0 on 2026-01-20 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultationsessionmodel_admission_and_more'),
        ('inpatient', '0007_admission_admission_activated_date_and_more'),
        ('patient', '0004_alter_registrationpaymentmodel_status'),
        ('service', '0003_servicecategory_specializations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientservicetransaction',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Name of walk-in customer (only used when patient is null)', max_length=200),
        ),
        migrations.AddField(
            model_name='patientservicetransaction',
            name='source',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('admission', 'Admission'), ('walkin', 'Walk-in Sale')], default='walkin', help_text='Source of this transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientservicetransaction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel'),
        ),
        migrations.AddIndex(
            model_name='patientservicetransaction',
            index=models.Index(fields=['source', 'status'], name='service_pat_source_2784c6_idx'),
        ),
    ]
