# Generated by Django 5.0 on 2025-09-15 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceitemstockmovement_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Item Batches',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='serviceitemstockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='service.serviceitembatch'),
        ),
    ]
