# Generated by Django 6.0.2 on 2026-03-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0009_alter_admissiontask_task_type'),
        ('service', '0004_patientservicetransaction_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientservicetransaction',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Link to an admission record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='inpatient.admission'),
        ),
        migrations.AlterField(
            model_name='patientservicetransaction',
            name='surgery',
            field=models.ForeignKey(blank=True, help_text='Link to a surgery record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='inpatient.surgery'),
        ),
    ]
