# Generated by Django 5.0 on 2025-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceitembatch_serviceitemstockmovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientservicetransaction',
            name='quantity_dispensed',
            field=models.PositiveIntegerField(default=0, help_text='How many units of the item have been given to the patient.'),
        ),
    ]
