# Generated by Django 5.0 on 2025-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_patientservicetransaction_quantity_dispensed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientservicetransaction',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='patientservicetransaction',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('partially_dispensed', 'Partially Dispensed'), ('fully_dispensed', 'Fully Dispensed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
