# Generated by Django 5.0 on 2025-09-15 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_patientservicetransaction_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresult',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='service.patientservicetransaction'),
        ),
    ]
