# Generated by Django 5.0 on 2025-10-01 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('patient', '0002_initial'),
        ('scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalScanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(max_length=200)),
                ('scan_code', models.CharField(blank=True, max_length=20)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('clinical_indication', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, help_text='Upload external scan/radiology report (PDF/Image)', null=True, upload_to='external_scan_results/%Y/%m/')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('result_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_scan_orders', to='consultation.consultationsessionmodel')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_external_scans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_scan_orders', to='patient.patientmodel')),
                ('result_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_external_scan_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Scan Order',
                'verbose_name_plural': 'External Scan Orders',
                'db_table': 'external_scan_orders',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
