# Generated by Django 5.0 on 2025-09-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresultmodel',
            name='template',
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='scan.scanordermodel'),
            preserve_default=False,
        ),
    ]
