# Generated by Django 5.0 on 2025-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_externalscanorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanordermodel',
            options={'ordering': ['-ordered_at'], 'permissions': [('view_financial_report', 'Can view scan financial reports')]},
        ),
    ]
