# Generated by Django 5.0 on 2025-09-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_rename_patientmodel_admission_patient_and_more'),
        ('scan', '0002_remove_scanresultmodel_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanordermodel',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Link to an admission record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_orders', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='scanordermodel',
            name='surgery',
            field=models.ForeignKey(blank=True, help_text='Link to a surgery record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_orders', to='inpatient.surgery'),
        ),
    ]
