# Generated by Django 5.0 on 2025-09-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_rename_consultation_notes_consultationsessionmodel_assessment'),
        ('scan', '0003_scanordermodel_admission_scanordermodel_surgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanordermodel',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_consultation_order', to='consultation.consultationsessionmodel'),
        ),
    ]
