# Generated by Django 5.0 on 2025-11-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_alter_scanordermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanordermodel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('wallet', 'Patient Wallet'), ('admission', 'Admission Deposit'), ('insurance', 'Insurance')], default='cash', max_length=20),
        ),
    ]
