# Generated by Django 5.0 on 2025-09-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('scan', '0004_scanordermodel_consultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresultmodel',
            options={'ordering': ['-performed_at']},
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='advance_booking_days',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='default_appointment_duration',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='department_head',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='reminder_hours_before',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='send_appointment_reminders',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='scansettingmodel',
            name='working_hours_start',
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='extracted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_scan_reports', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Optional: Key measurements extracted from report image\n        {\n            "key_findings": ["Heart size normal", "Lung fields clear"],\n            "measurements": [\n                {"parameter": "Heart size", "value": "Normal"},\n                {"parameter": "Lung fields", "value": "Clear bilaterally"}\n            ]\n        }\n        '),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='radiology_report_image',
            field=models.ImageField(blank=True, help_text='Uploaded radiology report (for better readability)', null=True, upload_to='radiology_reports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='report_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='technician_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scans', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='allow_direct_scan_order',
            field=models.BooleanField(default=False, help_text='Allow patients to order lab tests directly without a consultation (walk-in).'),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='allow_result_print_in_scan',
            field=models.BooleanField(default=True, help_text='Allow staff in the scan department to print test results.'),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='allow_result_printing_by_consultant',
            field=models.BooleanField(default=True, help_text='Allow the ordering consultant/doctor to print test results from their dashboard.'),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='scan_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scansettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='scanresultmodel',
            table='scan_results',
        ),
    ]
