# Generated by Django 5.0 on 2025-09-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_alter_scanresultmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanordermodel',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanordermodel',
            name='payment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_scan_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanordermodel',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanordermodel',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Scheduled'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
