# Generated by Django 5.0 on 2026-01-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_scanordermodel_customer_name_scanordermodel_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanordermodel',
            name='source',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('admission', 'Admission'), ('walkin', 'Walk-in')], default='consultation', help_text='Source of this scan order', max_length=20),
        ),
    ]
