# Generated by Django 5.0 on 2025-09-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('scan', '0006_alter_scanordermodel_ordered_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresultmodel',
            name='patient',
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='measured_values',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Actual measured values matching template structure:\n        {\n            "measurements": [\n                {\n                    "code": "HR",\n                    "value": 85,\n                    "unit": "bpm", \n                    "normal": true,\n                    "comment": "Within normal limits"\n                }\n            ],\n            "technical_factors": {\n                "kvp": 120,\n                "mas": 100,\n                "exposure_time": "0.5s"\n            }\n        }\n        '),
        ),
        migrations.AddField(
            model_name='scanresultmodel',
            name='report_date',
            field=models.DateTimeField(blank=True, help_text='When report was finalized', null=True),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Key findings extracted from report image:\n        {\n            "key_findings": ["Heart size normal", "Lung fields clear"],\n            "abnormalities": [],\n            "follow_up_required": false\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='findings',
            field=models.TextField(blank=True, help_text='Primary scan findings'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='impression',
            field=models.TextField(blank=True, help_text='Clinical impression/diagnosis'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_scan_results', to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='radiology_report_image',
            field=models.ImageField(blank=True, help_text='Uploaded radiology report image', null=True, upload_to='radiology_reports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Follow-up recommendations'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('finalized', 'Finalized'), ('amended', 'Amended')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='technician_comments',
            field=models.TextField(blank=True, help_text='Technical notes'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scan_results', to='human_resource.staffmodel'),
        ),
    ]
