# Generated by Django 5.0 on 2025-09-11 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_remove_scanresultmodel_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresultmodel',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_scan_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scan_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
