# Generated by Django 5.0 on 2025-09-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_alter_scanresultmodel_performed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantemplatemodel',
            name='equipment_required',
        ),
        migrations.RemoveField(
            model_name='scantemplatemodel',
            name='preparation_required',
        ),
    ]
