# Generated by Django 5.0 on 2025-09-12 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_remove_scantemplatemodel_equipment_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresultmodel',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scan.scanordermodel'),
        ),
    ]
