# Generated by Django 5.0 on 2025-09-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0010_alter_scanresultmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresultmodel',
            name='radiologist_comments',
            field=models.TextField(blank=True, help_text='Interpretation and comments from the verifying radiologist'),
        ),
        migrations.AlterField(
            model_name='scanresultmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('finalized', 'Finalized'), ('amended', 'Amended')], default='draft', max_length=20),
        ),
    ]
