# Generated by Django 5.0 on 2025-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0011_scanresultmodel_radiologist_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresultmodel',
            options={'ordering': ['-performed_at'], 'permissions': [('can_verify_scan_result', 'Can verify Image result')]},
        ),
    ]
