# Generated by Django 5.0 on 2025-08-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_alter_consultationpaymentmodel_amount_due_and_more'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='payment_pk',
        ),
        migrations.CreateModel(
            name='RegistrationFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient_type', models.CharField(choices=[('old', 'OLD'), ('new', 'NEW')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_fee_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_fee_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('title', 'patient_type')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('old_card_number', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], max_length=50)),
                ('consultation_paid', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('consultation_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_consultation_fee', to='consultation.consultationfeemodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('registration_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.registrationfeemodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='registration_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.registrationpaymentmodel'),
        ),
    ]
