# Generated by Django 5.0 on 2025-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmodel',
            options={'permissions': [('can_view_patient_dashboard', 'Can view Patient Dashboard')]},
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='card_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
