# Generated by Django 5.0 on 2025-09-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='consultation_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_consultation_fee', to='consultation.consultationfeemodel'),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_payment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='registration_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.registrationfeemodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='registration_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='patient.registrationpaymentmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationfeemodel',
            unique_together={('title', 'patient_type')},
        ),
    ]
