# Generated by Django 5.0 on 2025-08-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patientmodel_payment_pk_registrationfeemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='consultation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='cash', max_length=20),
        ),
    ]
