# Generated by Django 5.0 on 2025-11-30 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='reason_for_revert',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_payment_reverted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('reverted', 'REVERTED')], default='active', max_length=200),
        ),
    ]
