# Generated by Django 5.0 on 2025-09-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientidgeneratormodel',
            name='single_patient_generator_record',
        ),
    ]
