# Generated by Django 5.0 on 2025-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_registrationpaymentmodel_consultation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpaymentmodel',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50),
        ),
    ]
