# Generated by Django 5.0 on 2025-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_registrationpaymentmodel_reason_for_revert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpaymentmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('reverted', 'REVERTED')], default='confirmed', max_length=200),
        ),
    ]
