# Generated by Django 5.0 on 2026-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_registrationpaymentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpaymentmodel',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('reverted', 'REVERTED')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationpaymentmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('pending', 'CONFIRMED'), ('reverted', 'REVERTED')], default='confirmed', max_length=200),
        ),
    ]
