# Generated by Django 5.0 on 2025-08-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_alter_consultationpaymentmodel_amount_due_and_more'),
        ('patient', '0004_alter_registrationpaymentmodel_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpaymentmodel',
            name='consultation_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_consultation_fee', to='consultation.consultationfeemodel'),
        ),
    ]
