# Generated by Django 5.0 on 2025-08-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_registrationpaymentmodel_consultation_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationpaymentmodel',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='patientsettingmodel',
            old_name='patient_registration_without_payment',
            new_name='generate_new_card_number',
        ),
        migrations.AlterField(
            model_name='registrationpaymentmodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
