# Generated by Django 5.0 on 2026-01-27 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultationsessionmodel_admission_and_more'),
        ('patient', '0005_alter_registrationpaymentmodel_registration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('age_min', models.IntegerField(blank=True, help_text='Minimum age (leave blank for no minimum)', null=True)),
                ('age_max', models.IntegerField(blank=True, help_text='Maximum age (leave blank for no maximum)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(help_text='Primary diagnosis to track', on_delete=django.db.models.deletion.CASCADE, to='consultation.diagnosisoption')),
            ],
            options={
                'verbose_name': 'Consultation Report Template',
                'verbose_name_plural': 'Consultation Report Templates',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('age_min', models.IntegerField(blank=True, help_text='Minimum age (leave blank for no minimum)', null=True)),
                ('age_max', models.IntegerField(blank=True, help_text='Maximum age (leave blank for no maximum)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], help_text='Leave blank for all genders', max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'SINGLE'), ('married', 'MARRIED'), ('widowed', 'WIDOWED'), ('divorced', 'DIVORCED')], help_text='Leave blank for all statuses', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Report Template',
                'verbose_name_plural': 'Registration Report Templates',
                'ordering': ['title'],
            },
        ),
    ]
