# Generated by Django 5.0 on 2025-08-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_registrationpaymentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='registration_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='patient.registrationpaymentmodel'),
        ),
    ]
