# Generated by Django 5.0 on 2025-08-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfomodel',
            name='emergency_contact',
        ),
    ]
