# Generated by Django 5.0 on 2025-08-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('human_resource', '0002_alter_hodmodel_deputy_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to='human_resource.staffmodel'),
        ),
    ]
