# Generated by Django 5.0 on 2025-09-01 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('human_resource', '0001_initial'),
        ('insurance', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='consultationfeemodel',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurance.hmocoverageplanmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultationfeemodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='insurance_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceclaimmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_payments', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='patient_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.patientinsurancemodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationroommodel',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='consultation.consultationblockmodel'),
        ),
        migrations.AddField(
            model_name='consultantmodel',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants', to='consultation.consultationroommodel'),
        ),
        migrations.AddField(
            model_name='doctorschedulemodel',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='consultation.consultantmodel'),
        ),
        migrations.AddField(
            model_name='patientqueuemodel',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.consultantmodel'),
        ),
        migrations.AddField(
            model_name='patientqueuemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='patientqueuemodel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultationpaymentmodel'),
        ),
        migrations.AddField(
            model_name='patientqueuemodel',
            name='vitals_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultation.patientqueuemodel'),
        ),
        migrations.AddField(
            model_name='patientvitalsmodel',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='consultation.patientqueuemodel'),
        ),
        migrations.AddField(
            model_name='patientvitalsmodel',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationroommodel',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Primary specialization for this room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.specializationmodel'),
        ),
        migrations.AddField(
            model_name='consultationfeemodel',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='consultation.specializationmodel'),
        ),
        migrations.AddField(
            model_name='consultantmodel',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.specializationmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedulemodel',
            unique_together={('consultant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='consultationroommodel',
            unique_together={('name', 'block')},
        ),
        migrations.AlterUniqueTogether(
            name='consultationfeemodel',
            unique_together={('specialization', 'patient_category', 'insurance')},
        ),
    ]
