# Generated by Django 5.0 on 2025-11-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisoption',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='secondary_diagnoses',
            field=models.ManyToManyField(blank=True, help_text='Additional diagnoses for this consultation', related_name='secondary_consultations', to='consultation.diagnosisoption'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='specializations',
            field=models.ManyToManyField(help_text='Specializations that can use this diagnosis', related_name='diagnosis_options', to='consultation.specializationmodel'),
        ),
    ]
