# Generated by Django 5.0 on 2025-11-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_diagnosisoption_options_and_more'),
        ('inpatient', '0005_alter_admission_admission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='For inpatient ward rounds', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='inpatient.admission'),
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='vitals',
            field=models.JSONField(blank=True, help_text='Patient vitals: {"bp": "120/80", "temp": 37.2, "pulse": 72, "spo2": 98, "weight": 70}', null=True),
        ),
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='assessment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='chief_complaint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='queue_entry',
            field=models.OneToOneField(blank=True, help_text='For OPD consultations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultation.patientqueuemodel'),
        ),
        migrations.AddConstraint(
            model_name='consultationsessionmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admission__isnull', True), ('queue_entry__isnull', False)), models.Q(('admission__isnull', False), ('queue_entry__isnull', True)), _connector='OR'), name='either_queue_or_admission'),
        ),
    ]
