# Generated by Django 5.0 on 2025-09-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_initial'),
        ('finance', '0005_financesettingmodel_minimum_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientqueuemodel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.patienttransactionmodel'),
        ),
        migrations.DeleteModel(
            name='ConsultationPaymentModel',
        ),
    ]
