# Generated by Django 6.0.2 on 2026-03-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultationsessionmodel_admission_and_more'),
        ('inpatient', '0009_alter_admissiontask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitalsmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='inpatient.admission'),
        ),
        migrations.AlterField(
            model_name='patientvitalsmodel',
            name='queue_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='consultation.patientqueuemodel'),
        ),
    ]
