# Generated by Django 5.0 on 2025-08-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultationfeemodel_insurance'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationfeemodel',
            unique_together={('specialization', 'patient_category', 'insurance')},
        ),
    ]
