# Generated by Django 5.0 on 2025-09-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_patientqueuemodel_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='follow_up_instructions',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='history_of_present_illness',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='investigations_ordered',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='medications_prescribed',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='past_medical_history',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='physical_examination',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='treatment_plan',
        ),
        migrations.RemoveField(
            model_name='consultationsessionmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='case_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing Treatment'), ('completed', 'Case Completed'), ('referred', 'Referred'), ('discharged', 'Discharged')], default='ongoing', help_text="Mark as 'completed' to make next visit a NEW consultation", max_length=20),
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='consultation_notes',
            field=models.TextField(default='dd', help_text='Comprehensive consultation notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='consultation_type',
            field=models.CharField(choices=[('new', 'New Patient'), ('follow_up', 'Follow-up Visit')], default='new', help_text='Only NEW consultations appear in OPD register', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='other_diagnosis_text',
            field=models.CharField(blank=True, help_text='If diagnosis not in list above', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='consultations/'),
        ),
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.patientqueuemodel'),
        ),
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AlterModelTable(
            name='consultationsessionmodel',
            table=None,
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='primary_diagnosis',
            field=models.ForeignKey(blank=True, help_text='Required for new consultations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_consultations', to='consultation.diagnosisoption'),
        ),
    ]
