# Generated by Django 5.0 on 2025-09-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_diagnosisoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsessionmodel',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultation.patientqueuemodel'),
        ),
    ]
