# Generated by Django 5.0 on 2025-08-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultationfeemodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationfeemodel',
            name='duration_minutes',
        ),
    ]
