# Generated by Django 5.0 on 2025-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_alter_consultationsessionmodel_queue_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='chief_complaint',
            field=models.TextField(default='pp', help_text='Comprehensive consultation notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationsessionmodel',
            name='diagnosis',
            field=models.TextField(default='ll', help_text='Comprehensive consultation notes'),
            preserve_default=False,
        ),
    ]
