# Generated by Django 5.0 on 2025-08-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_remove_consultationfeemodel_duration_minutes'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationfeemodel',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurance.patientinsurancemodel'),
        ),
    ]
