# Generated by Django 5.0 on 2025-09-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_consultationsessionmodel_chief_complaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationsessionmodel',
            old_name='consultation_notes',
            new_name='assessment',
        ),
    ]
