# Generated by Django 5.0 on 2025-08-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_alter_consultationfeemodel_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='insurance_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='patient_portion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('transfer', 'Transfer'), ('insurance', 'Insurance')], default='wallet', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overpaid', 'Overpaid')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientqueuemodel',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.consultantmodel'),
        ),
    ]
