# Generated by Django 5.0 on 2025-08-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_alter_consultationpaymentmodel_amount_due_and_more'),
        ('insurance', '0002_remove_hmocoverageplanmodel_coverage_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='insurance_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceclaimmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='patient_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.patientinsurancemodel'),
        ),
    ]
