# Generated by Django 5.0 on 2025-09-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_specializationgroupmodel_specializationmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationfeemodel',
            name='validity_in_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days this fee is valid after being applied.'),
        ),
    ]
