# Generated by Django 5.0 on 2025-09-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_consultationfeemodel_validity_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientqueuemodel',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.specializationmodel'),
        ),
    ]
