# Generated by Django 5.0 on 2025-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_patientqueuemodel_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitalsmodel',
            name='extra_note',
            field=models.TextField(blank=True),
        ),
    ]
