# Generated by Django 5.0 on 2025-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_patientvitalsmodel_extra_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitalsmodel',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvitalsmodel',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
